# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: request2.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='request2.proto',
  package='protobuf.common',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0erequest2.proto\x12\x0fprotobuf.common\"\xac\x01\n\x07\x61pidata\x12\x10\n\x08req_data\x18\x01 \x01(\x0c\x12\x12\n\nrequest_id\x18\x02 \x01(\t\x12\x1b\n\x13\x63orporation_site_id\x18\x03 \x01(\r\x12 \n\x18\x61nalysis_timeframe_start\x18\x04 \x01(\t\x12\x1e\n\x16\x61nalysis_timeframe_end\x18\x05 \x01(\t\x12\x1c\n\x14\x61nalysis_time_period\x18\x06 \x01(\rb\x06proto3')
)




_APIDATA = _descriptor.Descriptor(
  name='apidata',
  full_name='protobuf.common.apidata',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='req_data', full_name='protobuf.common.apidata.req_data', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='request_id', full_name='protobuf.common.apidata.request_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='corporation_site_id', full_name='protobuf.common.apidata.corporation_site_id', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='analysis_timeframe_start', full_name='protobuf.common.apidata.analysis_timeframe_start', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='analysis_timeframe_end', full_name='protobuf.common.apidata.analysis_timeframe_end', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='analysis_time_period', full_name='protobuf.common.apidata.analysis_time_period', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=208,
)

DESCRIPTOR.message_types_by_name['apidata'] = _APIDATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

apidata = _reflection.GeneratedProtocolMessageType('apidata', (_message.Message,), dict(
  DESCRIPTOR = _APIDATA,
  __module__ = 'request2_pb2'
  # @@protoc_insertion_point(class_scope:protobuf.common.apidata)
  ))
_sym_db.RegisterMessage(apidata)


# @@protoc_insertion_point(module_scope)
